
function qs(n){return new URLSearchParams(location.search).get(n)}
async function getSessionUser(){if(!window.supabaseClient)return null;const {data}=await supabaseClient.auth.getUser();return data?.user||null}
async function createSupportTicket(){const subject=document.getElementById('supportSubject')?.value||'Обращение',message=document.getElementById('supportBody')?.value||'',msg=document.getElementById('supportMsg');if(!message){msg.textContent='Напишите сообщение';return}const u=await getSessionUser();const {error}=await supabaseClient.from('support_tickets').insert({user_id:u?.id||null,subject,message,status:'new'});msg.textContent=error?error.message:'Заявка отправлена ✅'}
async function createListing(){const u=await getSessionUser();if(!u){openAuth();return}const payload={user_id:u.id,created_by:u.id,title:val('listingTitle'),category:val('listingCategory'),price:Number(val('listingPrice')||0),currency:val('listingCurrency')||'GEL',city:val('listingCity'),address:val('listingAddress'),latitude:Number(val('listingLatitude'))||null,longitude:Number(val('listingLongitude'))||null,description:val('listingDescription'),status:'active'};const {data,error}=await supabaseClient.from('listings').insert(payload).select().single();if(error)alert(error.message);else location.href='listing.html?id='+data.id}
function val(id){return document.getElementById(id)?.value||''}
async function loadListingDetail(){const id=qs('id');if(!id||!window.supabaseClient)return;const {data}=await supabaseClient.from('listings').select('*').eq('id',id).maybeSingle();if(!data)return;document.querySelectorAll('[data-title]').forEach(e=>e.textContent=data.title||'Объявление');document.querySelectorAll('[data-price]').forEach(e=>e.textContent=`${data.price||''} ${data.currency||'GEL'}`);document.querySelectorAll('[data-city]').forEach(e=>e.textContent=data.city||'');document.querySelectorAll('[data-description]').forEach(e=>e.textContent=data.description||'');if(data.latitude&&data.longitude)initListingMap(data.latitude,data.longitude)}
async function toggleFavorite(id){const u=await getSessionUser();if(!u){openAuth();return}const {error}=await supabaseClient.from('favorites').upsert({user_id:u.id,listing_id:id});alert(error?error.message:'Добавлено в избранное ✅')}
async function loadMyListings(){const box=document.getElementById('myListingsBox');if(!box)return;const u=await getSessionUser();if(!u){box.innerHTML='Войдите';return}const {data,error}=await supabaseClient.from('listings').select('*').eq('user_id',u.id).order('created_at',{ascending:false});if(error){box.innerHTML=error.message;return}box.innerHTML=(data||[]).map(card).join('')||'Нет объявлений'}
async function loadFavorites(){const box=document.getElementById('favoritesBox');if(!box)return;const u=await getSessionUser();if(!u){box.innerHTML='Войдите';return}const {data,error}=await supabaseClient.from('favorites').select('listings(*)').eq('user_id',u.id);if(error){box.innerHTML=error.message;return}box.innerHTML=(data||[]).map(x=>card(x.listings||{})).join('')||'Нет избранного'}
function card(x){return `<div class="listing-card"><h3>${x.title||'Объявление'}</h3><p>${x.city||''}</p><b>${x.price||''} ${x.currency||'GEL'}</b><a class="btn btn-light" href="listing.html?id=${x.id||''}">Открыть</a></div>`}
async function loadPayments(){const box=document.getElementById('paymentsBox');if(!box)return;const u=await getSessionUser();if(!u){box.innerHTML='Войдите';return}const {data,error}=await supabaseClient.from('payments').select('*').eq('user_id',u.id).order('created_at',{ascending:false});if(error){box.innerHTML=error.message;return}box.innerHTML=(data||[]).map(p=>`<div class="panel"><b>${p.description||p.type}</b><p>${p.amount||0} ${p.currency||'GEL'} · ${p.status}</p></div>`).join('')||'Нет операций'}
async function submitVerification(){const u=await getSessionUser();if(!u){openAuth();return}const {error}=await supabaseClient.from('verification_requests').insert({user_id:u.id,comment:val('verificationComment'),status:'pending'});alert(error?error.message:'Заявка отправлена ✅')}
async function createCargoOrder(){const u=await getSessionUser();if(!u){openAuth();return}const {error}=await supabaseClient.from('cargo_orders').insert({user_id:u.id,from_location:val('cargoFrom'),to_location:val('cargoTo'),cargo_type:val('cargoType'),weight:val('cargoWeight'),price:Number(val('cargoPrice')||0),status:'active'});alert(error?error.message:'Заявка опубликована ✅')}
async function createTravelRequest(){const u=await getSessionUser();const {error}=await supabaseClient.from('travel_requests').insert({user_id:u?.id||null,service_type:val('travelType'),destination:val('travelDestination'),people_count:Number(val('travelPeople')||1),phone:val('travelPhone'),comment:val('travelComment'),status:'new'});alert(error?error.message:'Заявка отправлена ✅')}
async function loadAdminTable(table,boxId){const box=document.getElementById(boxId);if(!box)return;const {data,error}=await supabaseClient.from(table).select('*').limit(100);if(error){box.innerHTML=error.message;return}box.innerHTML=(data||[]).map(x=>`<div class="panel"><pre style="white-space:pre-wrap">${JSON.stringify(x,null,2)}</pre></div>`).join('')||'Нет данных'}
