
let currentUser = null;
async function initAuth(){if(!window.supabaseClient)return null;const {data}=await supabaseClient.auth.getUser();currentUser=data?.user||null;updateAuthUI();return currentUser}
function updateAuthUI(){const l=document.getElementById("gbLoginBtn"),p=document.getElementById("gbProfileBtn"),o=document.getElementById("gbLogoutBtn");if(currentUser){if(l)l.style.display="none";if(p)p.style.display="inline-flex";if(o)o.style.display="inline-flex"}else{if(l)l.style.display="inline-flex";if(p)p.style.display="none";if(o)o.style.display="none"}}
function openAuth(){let m=document.getElementById("authModal");if(!m){m=document.createElement("div");m.id="authModal";m.className="modal";m.innerHTML=`<div class="modal-card"><h2>Вход / регистрация</h2><div class="field"><label>Email</label><input id="authEmail" type="email"></div><div class="field"><label>Пароль</label><input id="authPassword" type="password"></div><button class="btn btn-blue" onclick="loginUser()">Войти</button><button class="btn btn-orange" onclick="registerUser()">Создать аккаунт</button><button class="btn btn-light" onclick="closeAuth()">Закрыть</button><p id="authMessage"></p></div>`;document.body.appendChild(m)}m.classList.add("show")}
function closeAuth(){document.getElementById("authModal")?.classList.remove("show")}
async function loginUser(){const email=document.getElementById("authEmail")?.value||"",password=document.getElementById("authPassword")?.value||"",msg=document.getElementById("authMessage");if(!email||!password){msg.textContent="Введите email и пароль";return}const {data,error}=await supabaseClient.auth.signInWithPassword({email,password});if(error){msg.textContent=error.message;return}currentUser=data.user;msg.textContent="Вход выполнен ✅";updateAuthUI();setTimeout(()=>closeAuth(),600)}
async function registerUser(){const email=document.getElementById("authEmail")?.value||"",password=document.getElementById("authPassword")?.value||"",msg=document.getElementById("authMessage");if(!email||!password){msg.textContent="Введите email и пароль";return}const {data,error}=await supabaseClient.auth.signUp({email,password});if(error){msg.textContent=error.message;return}currentUser=data.user;msg.textContent="Регистрация создана ✅";updateAuthUI()}
async function logoutUser(){if(window.supabaseClient)await supabaseClient.auth.signOut();currentUser=null;localStorage.clear();sessionStorage.clear();updateAuthUI();location.href="index.html?v=logout"}
document.addEventListener("DOMContentLoaded",()=>initAuth())
